import React, { useEffect, useState } from 'react';
import { DataTable, StyledUsers, UserData } from './GetAllCoupons.styled';
import { ThemeProvider } from 'styled-components';
import dateFormat from 'dateformat';
import { theme } from '../../../theme';
import { getallcoupons } from '../../../services/coupon_service';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const GetAllCoupons = () => {
	const [coupon, setCoupon] = useState([]);

	useEffect(() => {
		let mounted = true;
		getallcoupons(localStorage.getItem('admin'), localStorage.getItem('role'))
			.then(items => {
				if (mounted) {
					if (items.status === "OK") {
						setCoupon(items.data)
					} else {
						toast.error(items.data.error);
					}
				}
			})
		return () => mounted = false;
	}, []);
	return (
		<div>
			<ThemeProvider theme={theme}>
				<ToastContainer
					position="top-right"
					autoClose={7000}
					hideProgressBar={false}
					newestOnTop={false}
					closeOnClick
					rtl={false}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="colored"
				/>
				<StyledUsers className="card p-5">
					<UserData className="card-body mx-auto">

						<DataTable className="table mt-3">
							<thead>
								<tr>
									<th scope="col">Date</th>
									<th scope="col">Generated by</th>
									<th scope="col">Coupon code</th>
									<th scope="col">Discount</th>
									<th scope="col">Validity</th>
									<th scope="col">Status</th>
								</tr>
							</thead>
							<tbody>
								{coupon.map((coupon, key) => (
									<tr key={key}>
										<td>{dateFormat(new Date(coupon.c_created_date), "d mmm yyyy")}</td>
										<td>{coupon.name}</td>
										<td>{coupon.coupon_code}</td>
										{coupon.discount_type === 0 ? <td>{coupon.discount_value} %</td> : <td>{coupon.discount_value} &#8377;</td>}
										<td>Valid for {coupon.valid_times} times for {coupon.valid_days} days</td>
										<td>{coupon.status}</td>
									</tr>
								))}
							</tbody>
						</DataTable>
					</UserData>
				</StyledUsers>
			</ThemeProvider>
		</div>
	);
}

GetAllCoupons.propTypes = {

};

export default GetAllCoupons;