import React from 'react'
import "../Coupon/Couponcode.scss"

export const Couponcode = () => {
  return (
    <div>

      {/* Main Layout */}
      <div className="card mx-auto my-auto">
        <div className="card-body align-items-center my-auto mx-auto">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="head1" scope="col">Date</th>
                <th class="head1" scope="col">Generated by</th>
                <th class="head1" scope="col">Coupon code</th>
                <th class="head1" scope="col">%off</th>
                <th class="head1" scope="col">Validity</th>
                <th class="head1" scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="bod1" scope="row">00 000 00</td>
                <td>aaa</td>
                <td>BRB45</td>
                <td>45%</td>
                <td>Valid for 10 times for 3 days</td>
                <td><button type="button" class="btn  btn-outline-primary">Active</button></td>
              </tr>
              <tr>
                <td class="bod1" scope="row">00 000 00</td>
                <td>bbb</td>
                <td>NEW50</td>
                <td>45%</td>
                <td>applied 2 times</td>
                <td><button type="button" class="btn btn-outline-secondary">Expired</button></td>
              </tr>
              <tr>
                <td class="bod1" scope="row">00 000 00</td>
                <td>ccc</td>
                <td>FREE50</td>
                <td>45%</td>
                <td>Valid for 5 times for 75 days</td>
                <td><button type="button" class="btn  btn-outline-primary">Active</button></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>



      {/* Coupon code Reedem */}
      {/* <div class="card text w-25 h-50  mx-5 my-5">
        <nav class="navbar navbar-light shadow p-3 mb-5 bg-body rounded ">
          <div class="container-fluid justify-content-between">
            <div>
              <button type="button" class="btn-close" aria-label="Close"></button>
              <a class="navbar-brand fw-bold mx-3" href="#">Generate Coupon Reedem</a>
            </div>
          </div>
        </nav>
        <ul class="list-group list-group-flush list1 ">
          <li>
            <div class="row">
              <div className='col lg-12 red'>Date</div>
              <div className='col lg-12 red'>Bussiness Name</div>
            </div>
          </li><br />
          <li>
            <div class="row">
              <div className='col lg-12'>00 000 00</div>
              <div className='col lg-12'>aaa</div>
            </div>
          </li><br />

          <li >
            <div class="row">
              <div className='col lg-12'>00 000 00</div>
              <div className='col lg-12'>bbb</div>
            </div>
          </li><br />

          <li >
            <div class="row">
              <div className='col lg-12'>00 000 00</div>
              <div className='col lg-12'>ccc</div>
            </div>
          </li><br />

          <li >
            <div class="row">
              <div className='col lg-12'>00 000 00</div>
              <div className='col lg-12'>ddd</div>
            </div>
          </li><br />
        </ul>
      </div> */}


    </div>
  )
}

export default Couponcode